import { useState } from 'react';
import { Play, Trash2, Download, RotateCcw, AlertCircle } from 'lucide-react';
import { useMeeting } from './hooks/useMeeting';
import Sidebar from './components/Sidebar';
import ChatDisplay from './components/ChatDisplay';
import DecisionPanel from './components/DecisionPanel';
import './App.css';

const defaultConfig = {
  provider: 'groq',
  model: 'meta-llama/llama-4-scout-17b-16e-instruct',
  temperature: 0.7,
  usePremium: false,
  threadId: `meeting_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
};

function App() {
  const [query, setQuery] = useState('');
  const [config, setConfig] = useState(defaultConfig);
  const [debugInfo, setDebugInfo] = useState(null);
  
  const {
    loading,
    error,
    result,
    threadId,
    startMeeting,
    reset,
  } = useMeeting();

  const handleStartMeeting = async () => {
    if (!query.trim()) return;
    
    setDebugInfo(null);
    
    try {
      await startMeeting({
        query: query.trim(),
        provider: config.provider,
        usePremium: config.usePremium,
      });
    } catch (err) {
      setDebugInfo({
        message: err.message,
        response: err.response?.data,
        backendUrl: import.meta.env.VITE_API_URL || 'https://ai-board-backend-production.up.railway.app',
      });
    }
  };

  const handleClear = () => {
    setQuery('');
    setDebugInfo(null);
    reset();
  };

  const handleExport = () => {
    if (!result) return;
    
    // Create print-friendly content
    const messages = result.messages || result.result?.messages || [];
    const decision = result.result?.decision || result.decision || '';
    const query = result.query || result.result?.query || '';
    
    const printContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>AI Board Meeting - ${result.thread_id}</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; max-width: 800px; margin: auto; color: #333; }
          h1 { color: #1a1a1a; border-bottom: 3px solid #4f46e5; padding-bottom: 10px; }
          h2 { color: #4f46e5; margin-top: 30px; }
          .meta { color: #666; font-size: 14px; margin-bottom: 20px; }
          .query { background: #f3f4f6; padding: 15px; border-radius: 8px; margin-bottom: 30px; font-style: italic; }
          .message { margin-bottom: 20px; padding: 15px; border-left: 4px solid #4f46e5; background: #f9fafb; }
          .message-header { font-weight: bold; color: #4f46e5; margin-bottom: 5px; }
          .message-content { white-space: pre-wrap; line-height: 1.6; }
          .decision { background: #1a1a1a; color: white; padding: 25px; border-radius: 12px; margin-top: 30px; }
          .decision h2 { color: #a5b4fc; }
          .footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <h1>🤖 AI Board Meeting Report</h1>
        <div class="meta">
          <strong>Thread ID:</strong> ${result.thread_id}<br>
          <strong>Date:</strong> ${new Date().toLocaleString()}<br>
          <strong>Status:</strong> ${result.status || 'Completed'}
        </div>
        
        <h2>📋 Original Query</h2>
        <div class="query">${query}</div>
        
        <h2>💬 Board Discussion</h2>
        ${messages.map(msg => {
          const name = msg.name || msg.role || 'Unknown';
          const content = typeof msg.content === 'string' ? msg.content : JSON.stringify(msg.content);
          return `
            <div class="message">
              <div class="message-header">${name.replace('_', ' ').toUpperCase()}</div>
              <div class="message-content">${content}</div>
            </div>
          `;
        }).join('')}
        
        ${decision ? `
          <div class="decision">
            <h2>📌 Board Decision</h2>
            <div class="message-content">${decision}</div>
          </div>
        ` : ''}
        
        <div class="footer">
          Generated by AI Board of Directors • ${new Date().toLocaleDateString()}
        </div>
      </body>
      </html>
    `;
    
    // Open print dialog (can save as PDF)
    const printWindow = window.open('', '_blank');
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  const handleNewMeeting = () => {
    setQuery('');
    setDebugInfo(null);
    reset();
    setConfig({
      ...defaultConfig,
      threadId: `meeting_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
    });
  };

  const messages = result?.messages || result?.result?.messages || [];

  return (
    <div className="app">
      <Sidebar config={config} onConfigChange={setConfig} />
      
      <main className="main-content">
        {/* Header */}
        <header className="header">
          <h1>🏢 AI Board of Directors</h1>
          <p>Multi-Agent Business Decision Making</p>
        </header>

        {/* Query Input */}
        <section className="query-section">
          <h3>📋 Business Question</h3>
          <textarea
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Example: Should we invest $800k in expanding our AI product line next quarter?"
            rows={4}
            disabled={loading}
          />
          
          <div className="button-row">
            <button
              className="btn-primary"
              onClick={handleStartMeeting}
              disabled={loading || !query.trim()}
            >
              <Play size={20} />
              {loading ? 'Running Meeting...' : 'Start Board Meeting'}
            </button>
            
            <button className="btn-secondary" onClick={handleClear} disabled={loading}>
              <Trash2 size={18} />
              Clear
            </button>
          </div>
        </section>

        {/* Loading State */}
        {loading && (
          <div className="loading-state">
            <div className="spinner"></div>
            <p>Board members are deliberating...</p>
          </div>
        )}

        {/* Error Display */}
        {error && (
          <div className="error-display">
            <div className="error-header">
              <AlertCircle size={24} />
              <h3>Error Running Meeting</h3>
            </div>
            
            <details className="error-details">
              <summary>View Error Details</summary>
              <div className="error-content">
                <p><strong>Message:</strong> {error}</p>
                {debugInfo && (
                  <>
                    <p><strong>Backend URL:</strong> {debugInfo.backendUrl}</p>
                    {debugInfo.response && (
                      <p><strong>Server Response:</strong></p>
                    )}
                  </>
                )}
              </div>
            </details>
          </div>
        )}

        {/* Success Message */}
        {result && !loading && !error && (
          <div className="success-display">
            🎉 Meeting completed! Thread ID: {result.thread_id}
          </div>
        )}

        {/* Chat Display */}
        {messages.length > 0 && (
          <section className="chat-section">
            <ChatDisplay messages={messages} />
          </section>
        )}

        {/* Decision Panel */}
        {result?.result?.decision && (
          <section className="decision-section">
            <DecisionPanel decision={result.result.decision} />
          </section>
        )}

        {/* Action Buttons */}
        {result && !loading && (
          <section className="actions-section">
            <button className="btn-action" onClick={handleExport}>
              <Download size={18} />
              Export JSON
            </button>
            <button className="btn-action" onClick={handleNewMeeting}>
              <RotateCcw size={18} />
              New Meeting
            </button>
          </section>
        )}
      </main>
    </div>
  );
}

export default App;
